In [1]:
import numpy as np

In [18]:
np.random.seed(0)
n_ag = 9
n_cl = 3
q = 2
ag_rand = np.random.permutation(n_ag)
ag_per_clust = n_ag // n_cl
calphas = [ag_rand[alpha * ag_per_clust : (alpha+1) * ag_per_clust] for alpha in range(n_cl)]
print(calphas)

[array([7, 2, 1]), array([4, 8, 6]), array([3, 0, 5])]


In [19]:
u_mes = np.repeat(np.arange(n_cl), q) + 10
print(u_mes)

[10 10 11 11 12 12]


In [20]:
idmat = np.eye(q)
m = np.zeros((n_ag, n_cl))
for i in range(n_ag):
    for alpha in range(n_cl):
        if i in calphas[alpha]:
            m[i, alpha] = 1
print(calphas)
print(m)

[array([7, 2, 1]), array([4, 8, 6]), array([3, 0, 5])]
[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [21]:
mplus = np.kron(m, idmat)
print(mplus)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [22]:
uaug = mplus @ u_mes
print(uaug)

[12. 12. 10. 10. 10. 10. 12. 12. 11. 11. 12. 12. 11. 11. 10. 10. 11. 11.]
